### ISSUE TITLE
セリフがないとエラーが発生する

### ISSUE THREAD

**Issue by chiroito** [h-kojima/slide2mp4#5]
ノートを以下のように設定
```
~~~TTS
~~~
```
このノートに対して、以下のエラーメッセージが出力されます。
```
ls: cannot access 'azure-xml/34-*.xml': No such file or directory
（略）
ls: cannot access 'azure-xml/34-*.xml': No such file or directory
sed: can't read json/34.json: No such file or directory
json/34.json has been created.
（略）
34-list-zhpvqc71n2x1n7q1.txt: No such file or directory
mp3/34.mp3 has been created.
（略）
Traceback (most recent call last):
  File "/mnt/c/work/slide/slide2mp4/lib/json2srt.py", line 46, in <module>
    while i <= num:
NameError: name 'num' is not defined. Did you mean: 'sum'?
srt/34.srt has been created.
mp4/34.mp4 has been created.
（略）
[Parsed_subtitles_0 @ 0x555850bc8400] Unable to open srt/34.srt
[AVFilterGraph @ 0x55585114cac0] Error initializing filter 'subtitles' with args 'srt/34.srt:force_style=FontName=NotoSansCJKjp-Regular,FontSize=14'
Error reinitializing filters!
Failed to inject frame into filter network: No such file or directory
Error while processing the decoded data for stream #0:0
```

**Comment by h-kojima** [comment]
現状では、何もセリフが指定されていない、つまり、音声データや字幕データのファイルサイズ0の場合は、こうしたエラーを表示して動画作成処理を停止するようにしています。

回避策としては、以下のように、一時停止(この例では3秒)するだけの音声データを作るだけのノートを指定して、slide2mp4実行時の字幕オプションを`--no-subtitles`オプションで無効化する、などがあります。
```
~~~TTS
~~~BREAK 3s
~~~
```

**Comment by chiroito** [comment]
`~~~BREAK`も試した増したが、4つ目のエラーは発生するようです。
エラー発生後も処理は継続しているようでした。
デフォルトで `bash` に `-e` オプションを付与した方が良いかもしれません。

```
Traceback (most recent call last):
  File "/mnt/c/work/slide/slide2mp4/lib/json2srt.py", line 46, in <module>
    while i <= num:
NameError: name 'num' is not defined. Did you mean: 'sum'?
srt/34.srt has been created.
```

**Comment by h-kojima** [comment]
下記のパッチで、`~~~BREAK 3s`などを使う場合、セリフを指定しなくても動画作成が正常に完了するようにしました。
こちらを試してみてください。
https://github.com/automating-presentations/slide2mp4/commit/457b6d616a1288e8cf34e480a6b86ec354d4fce0

なお、`~~~BREAK`も無い場合は、音声データのmp3ファイルそのものが作成されないため、下記のようなエラーを出力して処理を停止するようにしています。
```
ls: azure-xml/1-*.xml: No such file or directory
azure-mp3/1-1.mp3 is empty file.
Please check xml/1.xml, azure-xml/1-1.xml, Azure japaneast Region, your Azure account settings, Azure Speech subscription key in /XXX/.azure/tts-subs-keyfile.
```
